<template><div><h4 id="_1-如何使用sql语句实现增加、修改和删除" tabindex="-1"><a class="header-anchor" href="#_1-如何使用sql语句实现增加、修改和删除"><span>1.如何使用SQL语句实现增加、修改和删除？</span></a></h4>
<p><code v-pre>INSERT INTO 表明 (列1,...) VALUES (值1,...)</code></p>
<div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code class="language-sql"><span class="line"><span class="token keyword">INSERT</span> <span class="token keyword">INTO</span> <span class="token identifier"><span class="token punctuation">`</span>Articles<span class="token punctuation">`</span></span> <span class="token punctuation">(</span><span class="token identifier"><span class="token punctuation">`</span>title<span class="token punctuation">`</span></span><span class="token punctuation">,</span> <span class="token identifier"><span class="token punctuation">`</span>content<span class="token punctuation">`</span></span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">VALUES</span> <span class="token punctuation">(</span><span class="token string">'静夜思'</span><span class="token punctuation">,</span> <span class="token string">'床前明月光，疑是地上霜。'</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="_2-sql语句的语法规则" tabindex="-1"><a class="header-anchor" href="#_2-sql语句的语法规则"><span>2.SQL语句的语法规则</span></a></h4>
<p><strong>大小写</strong>：这条SQL语句，都使用了大写字母改为小写也是一样可以正确运行的，只是大写的更规范一些而已。</p>
<p><strong>反引号</strong>： 表的名字和字段的名字，规范来说最好加上`号。</p>
<p><strong>引号</strong>：内容都是字符串，一定要加上引号。不加上引号的话，MySQL就无法正确的识别为字符串，也会报错的。当然，如果是数字的话，就不用打引号了。</p>
<div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code class="language-sql"><span class="line"><span class="token comment">-- 多行插入</span></span>
<span class="line"><span class="token keyword">INSERT</span> <span class="token keyword">INTO</span> 表名 <span class="token punctuation">(</span>列<span class="token number">1</span><span class="token punctuation">,</span> <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">VALUES</span> <span class="token punctuation">(</span>值<span class="token number">1</span><span class="token punctuation">,</span> <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">       <span class="token punctuation">(</span>值<span class="token number">1</span><span class="token punctuation">,</span> <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">INSERT</span> <span class="token keyword">INTO</span> <span class="token identifier"><span class="token punctuation">`</span>Articles<span class="token punctuation">`</span></span> <span class="token punctuation">(</span><span class="token identifier"><span class="token punctuation">`</span>title<span class="token punctuation">`</span></span><span class="token punctuation">,</span> <span class="token identifier"><span class="token punctuation">`</span>content<span class="token punctuation">`</span></span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">VALUES</span> <span class="token punctuation">(</span><span class="token string">'将进酒'</span><span class="token punctuation">,</span> <span class="token string">'天生我材必有用，千金散尽还复来。'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">       <span class="token punctuation">(</span><span class="token string">'宣州谢朓楼饯别校书叔云'</span><span class="token punctuation">,</span> <span class="token string">'抽刀断水水更流，举杯消愁愁更愁。'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">       <span class="token punctuation">(</span><span class="token string">'梦游天姥吟留别'</span><span class="token punctuation">,</span> <span class="token string">'安能摧眉折腰事权贵，使我不得开心颜！'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">       <span class="token punctuation">(</span><span class="token string">'春夜宴从弟桃花园序'</span><span class="token punctuation">,</span> <span class="token string">'天地者，万物之逆旅也；光阴者，百代之过客也。'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">       <span class="token punctuation">(</span><span class="token string">'宣州谢朓楼饯别校书叔云'</span><span class="token punctuation">,</span> <span class="token string">'弃我去者，昨日之日不可留；乱我心者，今日之日多烦忧。'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">       <span class="token punctuation">(</span><span class="token string">'庐山谣寄卢侍御虚舟'</span><span class="token punctuation">,</span> <span class="token string">'我本楚狂人，凤歌笑孔丘。手持绿玉杖，朝别黄鹤楼。'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">       <span class="token punctuation">(</span><span class="token string">'行路难'</span><span class="token punctuation">,</span> <span class="token string">'长风破浪会有时，直挂云帆济沧海'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">       <span class="token punctuation">(</span><span class="token string">'将进酒'</span><span class="token punctuation">,</span> <span class="token string">'人生得意须尽欢，莫使金樽空对月。天生我材必有用，千金散尽还复来。'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">       <span class="token punctuation">(</span><span class="token string">'望庐山瀑布'</span><span class="token punctuation">,</span> <span class="token string">'飞流直下三千尺，疑是银河落九天。'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">       <span class="token punctuation">(</span><span class="token string">'访戴天山道士不遇'</span><span class="token punctuation">,</span> <span class="token string">'树深时见鹿，溪午不闻钟。'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">       <span class="token punctuation">(</span><span class="token string">'清平调'</span><span class="token punctuation">,</span> <span class="token string">'云想衣裳花想容，春风拂槛露华浓。'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">       <span class="token punctuation">(</span><span class="token string">'春夜洛城闻笛'</span><span class="token punctuation">,</span> <span class="token string">'谁家玉笛暗飞声，散入春风满洛城。'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="修改语句" tabindex="-1"><a class="header-anchor" href="#修改语句"><span>修改语句</span></a></h4>
<div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code class="language-sql"><span class="line"><span class="token keyword">UPDATE</span> 表名</span>
<span class="line"><span class="token keyword">SET</span> 列<span class="token number">1</span><span class="token operator">=</span>值<span class="token number">1</span><span class="token punctuation">,</span></span>
<span class="line">    列<span class="token number">2</span><span class="token operator">=</span>值<span class="token number">2</span><span class="token punctuation">,</span> <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token keyword">WHERE</span> 条件</span>
<span class="line"></span>
<span class="line"><span class="token comment">-- 例如：</span></span>
<span class="line"><span class="token keyword">UPDATE</span> <span class="token identifier"><span class="token punctuation">`</span>Articles<span class="token punctuation">`</span></span></span>
<span class="line"><span class="token keyword">SET</span> <span class="token identifier"><span class="token punctuation">`</span>title<span class="token punctuation">`</span></span><span class="token operator">=</span><span class="token string">'黄鹤楼送孟浩然之广陵'</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token identifier"><span class="token punctuation">`</span>content<span class="token punctuation">`</span></span><span class="token operator">=</span><span class="token string">'故人西辞黄鹤楼，烟花三月下扬州。'</span></span>
<span class="line"><span class="token keyword">WHERE</span> <span class="token identifier"><span class="token punctuation">`</span>id<span class="token punctuation">`</span></span> <span class="token operator">=</span> <span class="token number">2</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="删除语句" tabindex="-1"><a class="header-anchor" href="#删除语句"><span>删除语句</span></a></h4>
<div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code class="language-sql"><span class="line"><span class="token keyword">DELETE</span></span>
<span class="line"><span class="token keyword">FROM</span> 表名</span>
<span class="line"><span class="token keyword">WHERE</span> 条件</span>
<span class="line"></span>
<span class="line"><span class="token comment">-- 例如：</span></span>
<span class="line"><span class="token keyword">DELETE</span></span>
<span class="line"><span class="token keyword">FROM</span> <span class="token identifier"><span class="token punctuation">`</span>ARTICLES<span class="token punctuation">`</span></span></span>
<span class="line"><span class="token keyword">WHERE</span> <span class="token identifier"><span class="token punctuation">`</span>id<span class="token punctuation">`</span></span> <span class="token operator">=</span> <span class="token number">5</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


